import { Url } from "./url";
import { Type } from "./type";
import { UI } from "./ui";
import { Model } from "./model";
import { View } from "./view";
import { Event } from "./event";
import { Ruler } from "./ruler";
import { Render } from "./render";
console.log("🚀 Slide Rule build script");
Type;
Url.initialize();
UI.initialize();
Model.initialize();
View.initialize();
Event.initialize();
Ruler.initialize();
Render.setRenderer(Ruler.renderer);
Render.markDirty();