import * as Url from "./url";
import * as Type from "./type";
import * as UI from "./ui";
import * as Model from "./model";
import * as View from "./view";
import * as Event from "./event";
import * as Ruler from "./ruler";
import * as Render from "./render";
console.log("🚀 Slide Rule build script");
Type;
Url.initialize();
UI.initialize();
Model.initialize();
View.initialize();
Event.initialize();
Ruler.initialize();
Render.setRenderer(Ruler.renderer);
Render.markDirty();
